### ISSUE TITLE
Undocumented/IIlegal 6502 Opcodes

### ISSUE THREAD

**Issue by XadNightfall** [hpwit/SID6581#15] opened 2021-05-08 08:45 UTC
Very nice project, i like it.

There is maybe a possibility can you add the illegal opcodes of the 6502 emulator, some SIDs use them.

ES: 

https://hvsc.csdb.dk/MUSICIANS/M/Mitch_and_Dane/Dane/Wasted_All_These_Years.sid
https://hvsc.csdb.dk/MUSICIANS/M/Mitch_and_Dane/Dane/Party_Horse.sid
https://hvsc.csdb.dk/MUSICIANS/L/Lft/Lunatico_Side_1.sid
https://hvsc.csdb.dk/MUSICIANS/M/Mitch_and_Dane/Dane/Intertwined.sid

. and so on.

Thanks.

**Comment by tobozo** [comment] 2021-05-08 12:04
hey @XadNightfall thanks for your feedback.

I didn't know those opcodes existed, so I'll just leave this here for future reference for @hpwit :

https://codebase64.org/doku.php?id=base:extra_instructions_of_the_65xx_series_cpu

**Comment by XadNightfall** [comment] 2021-05-08 13:50
Thanks,

also here: 

http://csdb.dk/getinternalfile.php/153783/NoMoreSecrets-NMOS6510UnintendedOpcodes-20162412.pdf

**Comment by hpwit** [comment] 2021-05-08 16:11
Nice thank you ;)
I will do an update asap.

**Comment by XadNightfall** [comment] 2021-05-10 20:24
Yep, i'm a bug hunter :-)

These PSID tunes don't play or play only one note.

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Treasure_is_All_Mine.sid
https://hvsc.csdb.dk/MUSICIANS/S/Schneider_Markus/VandaliSID.sid
http://csdb.dk/getinternalfile.php/210968/lastnightcjw.sid

in this case "Undocumented / IIlegal 6510 Opcodes" are not used.

I have personally disassembled the SID code, it seems a problem of stack pointer of the CPU emu (probably)

Obviously these sids are played regularly with all sidplayers.

thanks.

**Comment by tobozo** [comment] 2021-05-15 12:14
followup for #16

@XadNightfall thanks for your feedback

Please note there's a refactoring attempt on the `experm` branch of this repository, it messes up with the initial scope of the library so it won't be merged into the master until I get the approval from @hpwit and/or some feedback on the breaking changes, but it's stable enough to be used as a sandbox.

> problem of stack pointer of the CPU emu 

does it mean [this file](https://github.com/hpwit/SID6581/blob/experm/src/modules/MOS/MOS_Registers.h) needs editing ?

[ESP32-SIDView](https://github.com/tobozo/ESP32-SIDView) is currently the only project to make full use of the new features in that `experm` branch, please let me know if you need me to fix the examples sketch as those haven't been updated to the new syntax yet.

**Comment by XadNightfall** [comment] 2021-05-15 14:59
> 
> 
> followup for #16
> 
> @XadNightfall thanks for your feedback
> 
> Please note there's a refactoring attempt on the `experm` branch of this repository, it messes up with the initial scope of the library so it won't be merged into the master until I get the approval from @hpwit and/or some feedback on the breaking changes, but it's stable enough to be used as a sandbox.
> 
> > problem of stack pointer of the CPU emu
> 
> does it mean [this file](https://github.com/hpwit/SID6581/blob/experm/src/modules/MOS/MOS_Registers.h) needs editing ?
> 
> [ESP32-SIDView](https://github.com/tobozo/ESP32-SIDView) is currently the only project to make full use of the new features in that `experm` branch, please let me know if you need me to fix the examples sketch as those haven't been updated to the new syntax yet.

Hi Tobozo, no , i think it's a problem of the CPU emulator.

https://github.com/hpwit/SID6581/blob/master/src/SIDPLAYER.cpp

The actual CPU emulator is a porting jssid code by jhohertz. 

Trying the same SID Tunes on the jssid (Java SID Player) don't work, so i think it's a BUG that's been around for a long time and nobody ever noticed. 

The same thing for the undocumented/illegal opcodes that are missing in both projects, but in this case is not a bug but a features .

**Comment by tobozo** [comment] 2021-05-15 15:58
Thanks for the insight, there's not much I can do on that part of the project with my little knowledge of C64 registers, unless you have a patch to submit I'll wait for @hpwit's feedback on this.

**Comment by XadNightfall** [comment] 2021-05-15 16:15
I have experience in 6502/6510 and C64 and i am trying to debug the JAVA version of the CPU emulator, as it is practically the same (deebugging JAVA much easier) but i can't really understand where it crashes or loop, unlike of the missing opcodes that are immediately visible with the console log

https://github.com/jhohertz/jsSID/blob/develop/js/jssid.mos6510.js

Line: 628. 

or here:

https://github.com/hpwit/SID6581/blob/master/src/SIDPLAYER.cpp

Line: 716

and replace the console.log (disabled) with a sprintf.

**Comment by hpwit** [comment] 2021-05-15 17:51
Hello,
@XadNightfall  go ahead with the changes. I am not the most ‘educated’ in cpu emulator. 
let me know.

**Comment by tobozo** [comment] 2021-05-15 21:55
btw there's a [community gitter](https://gitter.im/hpwit_SID6581/community)

I'll add verbosity to unhandled instructions as suggested by @XadNightfall, and start collecting the data using the SID pointed out in this thread.

[edit] 

- Apparently all 3 'failing' SID having are also claiming to run on 8580, for which I know for sure it's usually filtered out as not supported by this driver indeed. As I have no idea what the differences are, I'll leave this be for the meantime.

- Caught my first 'illegal' instructions: 
 
```log
00:35:23.912 -> cpuParse(): Unknown opc(0xbf) cmd/ (0x38) / addr(0x0d)
00:35:23.945 -> cpuParse(): Unknown opc(0x8f) cmd/ (0x38) / addr(0x0d)

0xBF = LAX ?
0x8f = AXS ?

```

**Comment by XadNightfall** [comment] 2021-05-16 19:36
I did a couple of commit for the illegal opcodes, it would be nice if someone fix  the problem of the sids below that don't 'sound' I lost an afternoon but i don't have fixed :(

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Treasure_is_All_Mine.sid

https://hvsc.csdb.dk/MUSICIANS/S/Schneider_Markus/VandaliSID.sid

http://csdb.dk/getinternalfile.php/210968/lastnightcjw.sid

**Comment by tobozo** [comment] 2021-05-16 22:13
thanks! I can confirm the SID using illegal codes are now playing flawlessly

I've tried to play with the opcodes, It didn't seem to change anything, I'm not even sure I'm looking in the right direction

- Treasure_is_All_Mine.sid
  Play_addr = $5003, Init_addr = $5000 (song 2/2)
  Silence

- lastnightcjw.sid
  Play_addr = $1003, Init_addr = $1000 (song 1/1)
  Produces a "bump" sound then silence

- VandaliSID.sid
  Play_addr = $a003, Init_addr = $a000 (song 1/1)
  Silence


However, after comparing different opcode lists found on github, I found the opcode `0xEB` wasn't aliasing `0xE9` as it should.

Could missing aliases be the cause of these SID files not playing ?

**Comment by XadNightfall** [comment] 2021-05-17 06:11
The SBC 0xEB it is practically never used because it is a duplicate of 0xE9  but occupies one bytes instead of two. 

SBC      $E9       A <- (A) - M - ~C          (Immediate)      bytes 2/ time 2
SBC      $EB       A <- (A) - M - ~C          (Immediate)      bytes 1/ time 2

However for completeness we can add it.

However if you don't see "Unknown opc" from the log the opcodes are fine.

**Comment by hpwit** [comment] 2021-05-17 06:31
Great job @XadNightfall 
Thank you for your work. I will try to test it ASAP.  Sorry I wasn’t more involved in that part but really busy lately. 
i will look at these three songs. Certainly something wrong in my original code

**Comment by XadNightfall** [comment] 2021-05-17 06:44
Hi hpwit, the problem is 100% in the 6502/6510 emulation, because the same tracks don't work also with jsSID from where the emulator code was ported. 

On jsSID the problem is the same descripted by me and @tobozo.

I have personally installed the jsSID locally on my server to test.

**Comment by XadNightfall** [comment] 2021-05-17 08:42
SBC opcode Fixed.

Now playing correctly these SID tunes:

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Concert_tune_5.sid

http://csdb.dk/getinternalfile.php/210968/lastnightcjw.sid

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Out_Run.sid (from second: +/- 0:30)

https://hvsc.csdb.dk/MUSICIANS/C/C0zmo/Treasure_is_All_Mine.sid

**Comment by hpwit** [comment] 2021-05-17 09:14
Great !!
thank you
You can merge then. 
PS: do not forget to add your name in the code and in the readme :)

**Comment by tobozo** [comment] 2021-05-17 12:16
niiice !

This only leaves [VandaliSID.sid](https://hvsc.csdb.dk/MUSICIANS/S/Schneider_Markus/VandaliSID.sid) as the last enigma of this thread :-)

:warning: Apparently platformio has already [indexed the new code](https://platformio.org/lib/show/7250/SID6581) without the SBC fix.
Why platformio doesn't use the 'release' channel is beyond me, now there's a release of this library bundled with broken examples.

Rule of thumb: only ready-to-realase code should be pushed on the master branch, also all Travis tests should succeed before doing that otherwise platformio will just jump on it and publish an unfinished version out of it.

Now if we want to fix that quick, we can either disable travis tests and leave the broken examples along with the lack of support for some sid files using SBC opcode, or I can prepare a cleaner release.

State of the examples:

- `SidTunesFromSPIFF` is being rewritten (will push soon)
- `newSIDplayer` is being rewritten (adding HVSC basic demo,  will push soon)
- `sid_serial` should be rewritten
- `SIDMIDI` I can't test that as I have no MIDI instrument, however I can try using [USB_Soft_Host](https://github.com/tobozo/ESP32-USB-Soft-Host) and a regular keyboard 
- `SidPlayerControl` most of the functionalities are deprecated there, will be deleted

State of the library / roadmap :

- HVSC Parser/Indexer can be erratic when used outside SD/SD_MMC context
- SID_Instruments have only been [partially tested](https://github.com/tobozo/ESP32-SIDView/blob/master/modules/helpers/intro_sound.h)
- SID_Player task isn't thread safe, depending on the chose core it can collide with SD, TFT, I2C, it should be turned into an event emitter

I'll be publishing a release in the next hours.

[edit] all CI builds succeeded :partying_face:  
![image](https://user-images.githubusercontent.com/1893754/118491198-058e1980-b71f-11eb-83c2-ec9befe4fee8.png)

**Comment by tobozo** [comment] 2021-05-17 12:57
please @XadNightfall @hpwit post some pics of your SID builds :nerd_face: 

here's a [video of mine](https://www.youtube.com/watch?v=0y-omBL66jA)

**Comment by XadNightfall** [comment] 2021-05-17 13:17
I am experimenting with PIC32MX and ESP32 and also STM32 :O

Since i wrote a lot of code for PIC32 (based of a old project Hybrid SID) and i had problems with the emulation i wanted to experiment with ESP32 too, but it had the same problems! :D and at this point i realized that all 6502/6510 emulators based on the same code are bugged.

I am very happy to have contributed to this beautiful project by solving my problems as well.

I am doing a couple of prototypes with PIC32MX (as you can see from the attached link  , post and video) but it is not said that i don't change everything and use an ESP32 MCU with hpwit/SID6581. 

https://www.nightfallcrew.com/28/04/2021/how-was-born-the-project-the-return-of-the-hybrid-sid-player/
https://www.nightfallcrew.com/category/today/projects_repairs/sid-player-projects_repairs/

**Comment by hpwit** [comment] 2021-05-17 13:28
Hello @XadNightfall  @tobozo 

Thank both of you for your work in improving this library !! I am happy to see that what I have started is used :)
I will post too my pub but is not as nice a yours !!!
Maybe  I will find the issue with Vandalisid.sid :)
@tobozo is everything tin the master ?

**Comment by tobozo** [comment] 2021-05-17 14:15
@hpwit not yet, some tests are still ongoing before I merge this into the master and produce the new release

As all I can do is wait for the tests to complete, I'm working with the equivalent of mspaint :roll_eyes: on linux to create a concept logo for this project, haven't figured out the right colors yet though. 

<p align="center">
<img src="https://raw.githubusercontent.com/hpwit/SID6581/master/extras/project_logo.png" alt="SID6581 for ESP32 logo" width="512" />
</p>

**Comment by XadNightfall** [comment] 2021-05-17 14:56
@hpwit 

Why you have choosen to use only the 6581? using an external SID you could also use 8580 (just a couple of different components and voltage).

Example in my project i use both SID and with an analog switch (MAX 4544) i choose which one to listen (Both SID play at the same time)

The automatic switch is done with a pin of the MCU and a check of the SID model that i get from the SID file header. 

In your project, i really like the idea of having used the songhtlenght (MD5) for the duration of the sid, i miss this one and it is fixed at 3 minutes.

**Comment by XadNightfall** [comment] 2021-05-17 18:32
fixed also: https://hvsc.csdb.dk/MUSICIANS/S/Schneider_Markus/VandaliSID.sid

ASL Opcode:

not working: setflags(FLAG_Z,!wval&0xff);
working: setflags(FLAG_Z,!(wval&0xff));

later i commit.

**Comment by tobozo** [comment] 2021-05-17 18:42
@XadNightfall please use the upcoming 3.0.2-beta branch for any code change

**Comment by hpwit** [comment] 2021-05-18 16:23
Hello @XadNightfall 
maybe you've noticed (and maybe corrected it)  in the expert branch you have this 
```C
void MOS_CPU_Controls::branch( bool flag )
{
 if (flag) 
 	int8_t dist = (int8_t)getmem(pc++);    
            cycles += ((pc &amp; 0x100) != (wval &amp; 0x100)) ? 2 : 1; 	
           pc += dist; 
              }
        else { 
	pc++;
 }
}
```
it should be
```C
void MOS_CPU_Controls::branch( bool flag )
{
 if (flag) 
 	uInt8_t dist = (int8_t)getmem(pc++);    
//for the negative jumps
 if (dist & 0x80) {
    dist = 0 - ((~dist & 0xff) + 1);
  }

  wval= pc + dist;
  wval &= 0xffff;
            cycles += ((pc &amp; 0x100) != (wval &amp; 0x100)) ? 2 : 1; 	
           pc += dist; 
              }
        else { 
	pc++;
 }
}
```

**Comment by tobozo** [comment] 2021-05-18 16:36
please note the experm branch will soon be deleted, the base branch for upcoming version is 3.0.2-beta

alos creating a new branch to suggest code change is totally okay as long as the base is 3.0.2-beta

**Comment by XadNightfall** [comment] 2021-05-18 21:39
> it should be

Yep , much more sensate, my mistake.

**Comment by tobozo** [comment] 2021-05-19 00:39
hello @XadNightfall can you set your **Compiler Warnings** to **All** in your IDE preferences? 

![image](https://user-images.githubusercontent.com/1893754/118740114-569b2c00-b84b-11eb-82f6-7f4c93f711c4.png)

These are the settings used by the CI, making sure no hacky syntax is used in the library code :wink: 
Additionnally this may help you understand why the brackets you removed were there in the first place.
I've commited a fix for the missing brackets, don't forget to git pull :-)

**Closed as completed** 2021-09-13 14:54 UTC
